### ISSUE TITLE
Fails To Encrypt With AES

### ISSUE THREAD

**Issue by AtropineTearz** [RustCrypto/AEADs#354]
Hi,

I have been receiving errors when running the aes and chacha20 encryption algorithms.

```rust
impl AESEncryption {
    pub fn encrypt(password: String, data: String){
        let pass = hex::decode(password).expect("Failed To Decode Hexadecimal");

        let key = Key::from_slice(&pass); // 32-bytes
        let cipher = Aes256Gcm::new(key);


        // Nonce (256 bits)
        let randomness = OSRandom::rand_32().expect("Failed");
        let nonce = Nonce::from_slice(&randomness); // 12-bytes; unique per message

        let text = b"plaintext message";
        let ciphertext = cipher.encrypt(nonce,text.as_ref()).expect("Encryption Failure");
    }

}
```

Here is the error

```
running 1 test
thread 'tests::aes_test' panicked at 'assertion failed: `(left == right)`
  left: `32`,
 right: `12`', /Users/0xsilene/.cargo/registry/src/github.com-1ecc6299db9ec823/generic-array-0.14.4/src/lib.rs:559:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:160:17
   3: core::panicking::assert_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:117:5
   4: <&generic_array::GenericArray<T,N> as core::convert::From<&[T]>>::from
             at /Users/0xsilene/.cargo/registry/src/github.com-1ecc6299db9ec823/generic-array-0.14.4/src/lib.rs:559:9
   5: <T as core::convert::Into<U>>::into
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/convert/mod.rs:538:9
   6: generic_array::GenericArray<T,N>::from_slice
             at /Users/0xsilene/.cargo/registry/src/github.com-1ecc6299db9ec823/generic-array-0.14.4/src/lib.rs:541:9
   7: EncryptMyFiles::aes::AESEncryption::encrypt
             at ./src/aes.rs:47:21
   8: aes::tests::aes_test
             at ./tests/aes.rs:7:9
   9: aes::tests::aes_test::{{closure}}
             at ./tests/aes.rs:6:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  11: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test tests::aes_test ... FAILED

failures:

failures:
    tests::aes_test

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

error: test failed, to rerun pass '--test aes'
The terminal process "/bin/bash '-c', 'cargo test -- --nocapture aes_test'" terminated with exit code: 101.
```

Thanks.

**Comment by newpavlov** [comment]
Have you tried to examine your code a bit closer and the produced stack trace? It should be quite easy to find the reason behind the error. You pass 32 bytes, while code expects 12 bytes. Even in your code you have comments "Nonce (256 bits)" and "12-bytes; unique per message". Don't you see an inconsistency here?

**Comment by AtropineTearz** [comment]
Ah yes. I dont know how I looked over that. Thank you for the help.
